// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _webApiKey = String.fromEnvironment(
    'NEXRIDE_FIREBASE_WEB_API_KEY',
    defaultValue: 'AIzaSyCy3eR2_3xjz25kWIdxyYcc514VMjhp5NQ',
  );
  static const String _webAppId = String.fromEnvironment(
    'NEXRIDE_FIREBASE_WEB_APP_ID',
    defaultValue: '1:684231437366:web:6e1b737dee1c5457ec3c97',
  );
  static const String _webAuthDomain = String.fromEnvironment(
    'NEXRIDE_FIREBASE_WEB_AUTH_DOMAIN',
    defaultValue: 'nexride-8d5bc.firebaseapp.com',
  );
  static const String _webDatabaseUrl = String.fromEnvironment(
    'NEXRIDE_FIREBASE_WEB_DATABASE_URL',
    defaultValue: 'https://nexride-8d5bc-default-rtdb.firebaseio.com',
  );
  static const String _webMeasurementId = String.fromEnvironment(
    'NEXRIDE_FIREBASE_WEB_MEASUREMENT_ID',
    defaultValue: 'G-5S1Y9JNRPG',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Same default Realtime Database as rider app — keep in sync with `lib/firebase_options.dart`.
  static const String defaultRealtimeDatabaseUrl =
      'https://nexride-8d5bc-default-rtdb.firebaseio.com';

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPKbsKmUCfq0ylIAuekiVko_Gu6wWQse4',
    appId: '1:684231437366:android:ce00fc6559282fbaec3c97',
    messagingSenderId: '684231437366',
    projectId: 'nexride-8d5bc',
    storageBucket: 'nexride-8d5bc.firebasestorage.app',
    databaseURL: defaultRealtimeDatabaseUrl,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZYXBPJpPZ819PKkx3QiKAg9wPpeXMeUs',
    appId: '1:684231437366:ios:35109b0addb01811ec3c97',
    messagingSenderId: '684231437366',
    projectId: 'nexride-8d5bc',
    storageBucket: 'nexride-8d5bc.firebasestorage.app',
    iosBundleId: 'com.nexride.driver',
    databaseURL: defaultRealtimeDatabaseUrl,
  );

  static String get webAppId => _webAppId;
  static String get webAuthDomain => _webAuthDomain;
  static String get webDatabaseUrl => _webDatabaseUrl;
  static bool get webAppIdLooksLikeMobileConfig =>
      _webAppId.contains(':android:') || _webAppId.contains(':ios:');

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _webApiKey,
        appId: _webAppId,
        messagingSenderId: '684231437366',
        projectId: 'nexride-8d5bc',
        authDomain: _webAuthDomain,
        storageBucket: 'nexride-8d5bc.firebasestorage.app',
        databaseURL: _webDatabaseUrl,
        measurementId: _webMeasurementId.isEmpty ? null : _webMeasurementId,
      );
}
