platform :ios, '15.0'

minimum_ios_version = '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
require 'shellwords'

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'GoogleMaps', '8.4.0'
  pod 'GooglePlaces', '8.5.0'
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_ios_version
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_MICROPHONE=1',
      ]

    end

    next unless target.respond_to?(:source_build_phase) && target.source_build_phase

    target.source_build_phase.files.each do |file|
      next unless file.settings && file.settings['COMPILER_FLAGS']

      flags = Shellwords.shellsplit(file.settings['COMPILER_FLAGS'])
      next unless flags.delete('-GCC_WARN_INHIBIT_ALL_WARNINGS')

      file.settings['COMPILER_FLAGS'] = flags.join(' ')
    end
  end

  Dir.glob(
    File.join(
      installer.sandbox.root.to_s,
      '*',
      'src',
      'core',
      'lib',
      'promise',
      'detail',
      'basic_seq.h',
    ),
  ).each do |grpc_basic_seq_path|
    contents = File.read(grpc_basic_seq_path)
    patched = contents.gsub(
      'Traits::template CallSeqFactory',
      'Traits::CallSeqFactory',
    )
    next if patched == contents

    File.chmod(0o644, grpc_basic_seq_path)
    File.write(grpc_basic_seq_path, patched)
  end

  installer.aggregate_targets.map(&:user_project).uniq.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_ios_version
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
    project.save
  end
end
